@startuml
Event <|-- Conference
Event <|-- BoardMeeting
Person <|-- Member
Member <|-- BoardMember
BoardMeeting "0..*" -- "0..*" BoardMember : : attendsTo
Conference "0..*" -- "0..*" Person : attendsTo
Event "0..*" -- "0..*" Member : attendsTo
Location "1" -- "0..*" Event : isLocated in
AAUOC o-- "0..*" Location
AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person

class AAUOC {
newLocation(l:Location) : void;
newEvent(e:Event) : void;
newPerson(p:Person) : void;
informEvent(e:Event) : void;
register(m:Member,e:Event) : void;
}

class Member {
e-mail : String;
}

class BoardMember {
}

class Event {
date: Date;
description: String;
assign(l:Location) : void;
}

class Conference {
max_attendees : Integer;
}

class BoardMeeting {
}

class Location {
description : String;
address : String;
}

class Person {
name : String;
}
@enduml